version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - violetagg
  labels:
  - type/dependency-upgrade
  ignore:
  - dependency-name: io.projectreactor:reactor-core
    versions:
    - "> 3.2.5.RELEASE"
  - dependency-name: io.reactivex.rxjava2:rxjava
    versions:
    - "> 2.2.18, < 2.3"
  - dependency-name: org.junit.platform:junit-platform-launcher
    versions:
    - "> 1.0.0"
  # Versions > 5 require JDK17+
  - dependency-name: org.junit.jupiter:*
    versions:
    - "[6.a, 7]"
  rebase-strategy: disabled
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - violetagg
  labels:
  - type/dependency-upgrade
  rebase-strategy: disabled
