name: Release Drafter

on:
  push:
    branches:
      - master

permissions: {}

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: release-drafter/release-drafter@44a942e465867c7465b76aa808ddca6e0acae5da
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
