name: Release Drafter

on:
  push:
    branches:
      - master

permissions: {}

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: release-drafter/release-drafter@139054aeaa9adc52ab36ddf67437541f039b88e2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
