name: Release Drafter

on:
  push:
    branches:
      - master

permissions: {}

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: release-drafter/release-drafter@73b95fa1c286dfd6802a4f949b07dad6149f2b0f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
